package smppengine

import (
	"bytes"
	"io"
	"sync/atomic"

	"github.com/fiorix/go-smpp/smpp/pdu"
)

// nextDeliverSeq is a process-wide counter for the sequence_number this
// engine assigns to server-initiated deliver_sm PDUs — started well above
// any sequence number a client is likely to have generated by the time it
// receives one. Collisions are harmless either way (a mock never needs to
// correlate deliver_sm_resp back to anything), this just keeps the numbers
// looking distinct from the client's own in a packet capture.
var nextDeliverSeq uint32 = 1_000_000

func nextDeliverSequence() uint32 {
	return atomic.AddUint32(&nextDeliverSeq, 1)
}

// writeDeliverSM hand-encodes a deliver_sm PDU body directly, bypassing
// github.com/fiorix/go-smpp's pdu.NewDeliverSM(). That type's FieldList
// unconditionally includes udh_length/gsm_user_data between sm_length and
// short_message, but its OWN decode side (pdufield.List.Decode) only reads
// those bytes when esm_class's UDHI bit is set — an asymmetry in the
// library, not the SMPP spec. Since no concatenated-SMS UDH is ever sent
// here (esm_class stays 0, no UDHI flag), matching submit_sm's field
// layout instead (which the same library defines with no such fields at
// all) is both spec-correct and what a real receiver — including this same
// library's own client — actually expects on the wire. Confirmed against a
// real client library round-trip (see engine_test.go); using the library's
// own DeliverSM constructor corrupted the message by one leading byte.
func writeDeliverSM(w io.Writer, seq uint32, sourceAddr, destAddr, shortMessage string) error {
	body := new(bytes.Buffer)
	writeCString(body, "") // service_type
	body.WriteByte(0)      // source_addr_ton
	body.WriteByte(0)      // source_addr_npi
	writeCString(body, sourceAddr)
	body.WriteByte(0) // dest_addr_ton
	body.WriteByte(0) // dest_addr_npi
	writeCString(body, destAddr)
	body.WriteByte(0)      // esm_class
	body.WriteByte(0)      // protocol_id
	body.WriteByte(0)      // priority_flag
	writeCString(body, "") // schedule_delivery_time
	writeCString(body, "") // validity_period
	body.WriteByte(0)      // registered_delivery
	body.WriteByte(0)      // replace_if_present_flag
	body.WriteByte(0)      // data_coding
	body.WriteByte(0)      // sm_default_msg_id
	body.WriteByte(byte(len(shortMessage)))
	body.WriteString(shortMessage)

	hdr := &pdu.Header{ID: pdu.DeliverSMID, Seq: seq, Len: uint32(pdu.HeaderLen + body.Len())}
	if err := hdr.SerializeTo(w); err != nil {
		return err
	}
	_, err := w.Write(body.Bytes())
	return err
}

func writeCString(b *bytes.Buffer, s string) {
	b.WriteString(s)
	b.WriteByte(0)
}

func (s *session) writeDeliverSM(seq uint32, sourceAddr, destAddr, shortMessage string) error {
	s.writeMu.Lock()
	err := writeDeliverSM(s.conn, seq, sourceAddr, destAddr, shortMessage)
	s.writeMu.Unlock()
	if err == nil {
		s.reg.Touch(s.mockID, s.regID, 0, 1)
	}
	return err
}
